//! Raw FFI bindings to TensorRT 10.x.
//!
//! ## Architecture
//!
//! All bindings go through a hand-written pure-C bridge:
//! - `include/trt_bridge.h` — opaque `btrt_*_t*` handle API (no TRT/CUDA headers leak out)
//! - `src/logger_shim.cpp` — the ONLY unavoidable C++: `ShimLogger : public nvinfer1::ILogger`
//!   (Rust cannot subclass abstract C++ classes)
//! - `src/trt_bridge.cpp` — thin C wrappers over TRT runtime/engine/context/CUDA
//!
//! bindgen generates Rust FFI from `trt_bridge.h`. When TRT updates:
//! 1. `apt install` new TRT headers
//! 2. `cargo build -p trt-sys` — C++ compiler errors in trt_bridge.cpp point exactly to
//!    changed methods (enqueueV2→V3, Dims→Dims64, etc.)
//! 3. Fix those methods; bindgen regenerates the Rust side automatically
//! See UPDATING.md for the full checklist.

#![allow(unsafe_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

// btrt_* C bridge bindings (logger shim + runtime/engine/context/CUDA)
// Generated by bindgen from include/trt_bridge.h (includes logger_shim.h).
// This is the complete stable API consumed by the `trt/` safe-wrapper crate.
//
// Stub mode (docs.rs, or TRT_STUB=1 for hosted CI): a committed bindings
// snapshot is used instead and no native code is compiled or linked —
// check/clippy/doc work on machines without TensorRT.
#[cfg(not(trt_stub))]
include!(concat!(env!("OUT_DIR"), "/bridge_bindings.rs"));
#[cfg(trt_stub)]
include!("pregenerated_bindings.rs");

// In-process ONNX -> engine builder (feature = "builder", links nvonnxparser).
#[cfg(all(feature = "builder", not(trt_stub)))]
include!(concat!(env!("OUT_DIR"), "/builder_bindings.rs"));
#[cfg(all(feature = "builder", trt_stub))]
extern "C" {
    pub fn btrt_build_engine_from_onnx(
        logger: *mut btrt_logger_t,
        onnx_path: *const ::std::os::raw::c_char,
        fp16: i32,
        input_name: *const ::std::os::raw::c_char,
        min_dims: *const i64,
        opt_dims: *const i64,
        max_dims: *const i64,
        ndims: i32,
        workspace_bytes: i64,
        out_blob: *mut *mut u8,
        out_len: *mut usize,
    ) -> i32;
    pub fn btrt_blob_free(blob: *mut u8);
}

// ── Version constants ────────────────────────────────────────────────────────

/// Installed TensorRT version "MAJOR.MINOR.PATCH.BUILD", parsed from
/// NvInferVersion.h at build time.  Engine-cache keys depend on this.
pub const TENSORRT_VERSION: &str = env!("TENSORRT_VERSION");

#[cfg(test)]
#[path = "../trt_version.rs"]
mod trt_version_tests_impl;

#[cfg(test)]
mod tests {
    use super::trt_version_tests_impl::parse_trt_version_text;

    #[test]
    fn parses_literal_version_macros() {
        let header = "\
#define NV_TENSORRT_MAJOR 10\n\
#define NV_TENSORRT_MINOR 3\n\
#define NV_TENSORRT_PATCH 0\n\
#define NV_TENSORRT_BUILD 30\n";
        assert_eq!(parse_trt_version_text(header).as_deref(), Some("10.3.0.30"));
    }

    #[test]
    fn parses_enterprise_indirection() {
        let header = "\
#define TRT_MAJOR_ENTERPRISE 10\n\
#define TRT_MINOR_ENTERPRISE 13\n\
#define TRT_PATCH_ENTERPRISE 3\n\
#define TRT_BUILD_ENTERPRISE 9\n\
#define NV_TENSORRT_MAJOR TRT_MAJOR_ENTERPRISE //!< comment\n\
#define NV_TENSORRT_MINOR TRT_MINOR_ENTERPRISE //!< comment\n\
#define NV_TENSORRT_PATCH TRT_PATCH_ENTERPRISE //!< comment\n\
#define NV_TENSORRT_BUILD TRT_BUILD_ENTERPRISE //!< comment\n";
        assert_eq!(parse_trt_version_text(header).as_deref(), Some("10.13.3.9"));
    }

    #[test]
    fn rejects_missing_or_cyclic_version_macros() {
        let header = "\
#define NV_TENSORRT_MAJOR NV_TENSORRT_MAJOR\n\
#define NV_TENSORRT_MINOR 13\n\
#define NV_TENSORRT_PATCH 3\n";
        assert_eq!(parse_trt_version_text(header), None);
    }
}
